
Beispiel der Verwendung von tf.Variable() und tf.assign() in TensorFlow 2


In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.debugging.set_log_device_placement(True)
tf.test.gpu_device_name()

''

In [3]:
my_tensor = tf.Variable([[1, 2, 3], [4,5,6]])

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


In [4]:
# Erstes Beispiel
t = np.array([2]) 

In [5]:
# Äquivalent zu my_tensor = my_tensor * 2 
my_tensor = my_tensor * t
my_tensor = tf.square(my_tensor) / 4
my_tensor = my_tensor - 1
print("Ausgabe Beispiel 1:")
print(my_tensor)
tf.print(my_tensor)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Mul in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Square in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Cast in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op RealDiv in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Sub in device /job:localhost/replica:0/task:0/device:CPU:0
Ausgabe Beispiel 1:
tf.Tensor(
[[ 0.  3.  8.]
 [15. 24. 35.]], shape=(2, 3), dtype=float64)
Executing op StringFormat in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op PrintV2 in device /job:localhost/replica:0/task:0/device:CPU:0
[[0 3 8]
 [15 24 35]]


Ausgabe:
[[ 0.  3.  8.]
[15. 24. 35.]]

In [6]:
# Zweites Beispiel:
my_tensor = tf.Variable([[1, 2, 3], [4,5,6]])
my_second_tensor = my_tensor.assign([[0,0,7],[0,0,8]])
print("Ausgabe Beispiel 2:")
tf.print(my_second_tensor)

Ausgabe Beispiel 2:
Executing op StringFormat in device /job:localhost/replica:0/task:0/device:CPU:0
[[0 0 7]
 [0 0 8]]


Ausgabe:
[[0 0 7]
[0 0 8]]

In [7]:
# Platzieren einer Variable auf die erste Verfügbare GPU
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)
print(c)

Executing op MatMul in device /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [8]:
with tf.device("/device:GPU:0"):
  meine_variable = tf.Variable([1,2,3])
  meine_variable = meine_variable.assign([0,0,7])
  tf.print(meine_variable)

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StringFormat in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op PrintV2 in device /job:localhost/replica:0/task:0/device:CPU:0
[0 0 7]
