In [1]:
import numpy as np

In [2]:
# Es wird ein Vektor arr aus vier zufälligen Zahlen zwischen 0 und 1 generiert
arr = np.random.rand(4)
arr

array([0.40573563, 0.80976989, 0.23406562, 0.17251333])

In [3]:
# arr hat wieder andere Werte
arr = np.random.rand(4)
arr

array([0.92715495, 0.76024213, 0.47486182, 0.94914238])

In [4]:
# Jetzt wird der Zufallsgenerator mit einem festen Wert seed initialisiert
np.random.seed(23)

In [5]:
# arr hat einen zufälligen Wert, der aber reproduzierbar ist
arr = np.random.rand(4)
arr

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])

In [6]:
# Jetzt wird noch mal mit demselben seed gearbeitet ... 
np.random.seed(23)

In [7]:
# ... und arr hat denselben Wert wie eben.
arr = np.random.rand(4)
arr

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])